/*
CREATE : INSERT
READ : SELECT 
UPDATE : UPDATE 
DELETE : DELETE
*/

/* INSERT */
INSERT INTO mv_dt VALUES('Avatar',2009 );
INSERT INTO mv_d SET TITLE ="" , year =1995; /* another war */

/* UPDATE */
UPDATE movies SET ID=1 
WHERE TITLE="MATRIX";
SET SQL_SAFE_UPDATES = 0;

/* DELETE */
DELETE FROM movies
WHERE ID= 1 AND TITLE="MATRIX" ;