USE tshirts;
INSERT INTO items 
VALUES
(NULL,"4ME","IMG/img/shirts/shirt-101.jpg") ,   
(NULL,"MIKE","IMG/img/shirts/shirt-102.jpg"),
(NULL,"4MIKE","IMG/img/shirts/shirt-103.jpg"),
(NULL,"FORMIKE","IMG/img/shirts/shirt-104.jpg"),
 (NULL,"Code","IMG/img/shirts/shirt-109.jpg"),
 (NULL,"HTML5","IMG/img/shirts/shirt-110.jpg"),
 (NULL,"CSS 3","IMG/img/shirts/shirt-111.jpg"),
 (NULL,"HTML","IMG/img/shirts/shirt-112.jpg"),
  (NULL,"CSS 3","IMG/img/shirts/shirt-113.jpg"),
  (NULL,"<?PHP ?>","IMG/img/shirts/shirt-114.jpg"),
(NULL," </code>","IMG/img/shirts/shirt-115.jpg"),
(NULL,"<?PHP ?>","IMG/img/shirts/shirt-116.jpg"),
(NULL,"GET['HTTP']","IMG/img/shirts/shirt-117.jpg"),
(NULL,"MIKE","IMG/img/shirts/shirt-118.jpg"),
(NULL,"CSS 3","IMG/img/shirts/shirt-119.jpg"),
(NULL,"HTML 5","IMG/img/shirts/shirt-120.jpg"),
(NULL,"POST['ME']","IMG/img/shirts/shirt-121.jpg"),
(NULL,"<?PHP>","IMG/img/shirts/shirt-122.jpg"),
(NULL,"MIke","IMG/img/shirts/shirt-123.jpg"),
(NULL,"$Variable","IMG/img/shirts/shirt-124.jpg"),
(NULL,"CSS 3","IMG/img/shirts/shirt-125.jpg"),
(NULL,"!DOCTYPE","IMG/img/shirts/shirt-126.jpg"),
(NULL,"MIKE","IMG/img/shirts/shirt-127.jpg"),
(NULL,"GET['HTTPS']","IMG/img/shirts/shirt-128.jpg"),
(NULL,"GET['HTTPS']","IMG/img/shirts/shirt-129.jpg"),
(NULL,"HTML 5","IMG/img/shirts/shirt-130.jpg"),
(NULL," 4MIKE","IMG/img/shirts/shirt-131.jpg"),
(NULL," MIKE","IMG/img/shirts/shirt-132.jpg");